package com.unicornstudio.lanball.network.common;

public enum NetworkObjectType {
    PLAYER_JOIN,
    PLAYER_DISCONNECT,
    PLAYER_UPDATE,
    GET_PLAYERS_LIST,
    PLAYERS_LIST,
    PLAYER_CHANGE_TEAM,
    REMOTE_PLAYER,
    CREATE_REMOTE_PLAYERS,
    SERVER_STATE,
    BALL_UPDATE,
    MAP_LOAD,
    START_GAME,
    SELECT_BOX_UPDATE,
    BALL_KICK,
    GATE_CONTACT,
    MATCH_END,
    SCORE_UPDATE,
    START_POSITION,
    ROUND_RESET,
    BALL_CONTACT,
    KEY_PRESS
}
